title: "Minjae Kim"
description: "Research on capable, efficient, and adaptive LLM-based systems."
repository: "kmj200392/minjaekim.github.io"
url: "https://kmj200392.github.io"
baseurl: "/minjaekim.github.io"

markdown: kramdown
encoding: "utf-8"
timezone: Asia/Seoul

include:
  - _pages
  - assets

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - run_server.sh
  - vendor

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

author:
  name: "Minjae Kim"
  avatar: "https://avatars.githubusercontent.com/u/154658355?v=4"
  bio: "Undergraduate Student at Korea University"
  email:
  github: "kmj200392"
  googlescholar:
  linkedin:
  cv:
